- hosts: terraform-ansible
  task:
  - name: criando o arquivo
  copy: 
    dest: /home/ubuntu/index.html
    content: <h1> Hello World </h1>
  - name: criando servidor 
  shell: "nohub busybox httpd -f -p 8080 &"
